version: '3'

services:
  web-server:
    image: nginx:stable-alpine
    container_name: define-a-word-web-server
    ports:
    - "8088:80"
    volumes:
    - ./src:/var/www/app
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database

  database:
    image: mysql:5.7.22
    container_name: define-a-word-database
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: words
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: define-a-word-app
    volumes:
      - ./src:/var/www/app
    ports:
      - "9000:9000"

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    container_name: define-a-word-cron
    volumes:
    - ./src:/var/www/app