version: '3'

networks:
  define-a-word:

services:
  define-a-word-web-server:
    image: nginx:stable-alpine
    container_name: define-a-word-web-server
    ports:
    - "8088:80"
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - define-a-word-app
      - define-a-word-database
    networks:
      - define-a-word

  define-a-word-database:
    image: mysql:5.7.22
    container_name: define-a-word-database
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - define-a-word

  define-a-word-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: define-a-word-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - define-a-word